name: ServerDoctor
version: '${version}'
main: com.serverdoctor.paper.ServerDoctorPaperPlugin
api-version: '1.21'
author: ['LittleSophyy', "zNixFNA"]
description: Read-only Analyse-, Diagnose- und Monitoring-Plattform für Minecraft-Server.
website: https://github.com/shvquu/server-doctor
folia-supported: false

commands:
  serverdoctor:
    description: ServerDoctor Diagnose-Befehle
    usage: /serverdoctor <scan|report|tps|conflicts|security|recs|history>
    aliases: [sd, doctor]
    permission: serverdoctor.admin

permissions:
  serverdoctor.admin:
    description: Zugriff auf ServerDoctor-Diagnosebefehle
    default: op
